services:
  - type: web
    name: recommendation-generator
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: STREAMLIT_SERVER_PORT
        value: 10000
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false
      - key: PYTHONPATH
        value: /app
    healthCheckPath: /_stcore/health
    autoDeploy: true
